scorecard:
  # Setting a global scorecard option
  output: json
  bundle: deploy/olm-catalog/ibm-grafana-operator
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_grafana_cr.yaml"
        namespace: "ibm-common-services"
        crds-dir: "deploy/crds"
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_grafana_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-grafana-operator/0.0.1/ibm-grafana-operator.v0.0.1.clusterserviceversion.yaml"