apiVersion: operator.ibm.com/v1alpha1
kind: Grafana
metadata:
  name: ibm-monitoring
spec:
  service:
    type: NodePort
    ports:
      - name: grafana-service
        protocol: TCP
        port: 3000
  resources:
    grafana: 2
    router: 1
    dashboard: 1
  baseImage: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/grafana
  baseImageTag: v6.5.2-build.1
  routerImage: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-management-ingress
  routerImageTag: 2.5.1
  dashboardCtlImage: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/dashboard-controller
  dashboardCtlImageTag: v1.2.0-build.2
  initImage: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-initcontainer
  initImageTag: 1.0.0-build.2
  ipVersion: "4"
  isHub: false
  imagePullSecrets:
    - infra-registry-key
  tlsSecretName: ibm-monitoring-certs
  tlsClientSecretName: ibm-monitoring-client-certs