apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-grafana-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-grafana-operator
  template:
    metadata:
      labels:
        name: ibm-grafana-operator
    spec:
      serviceAccountName: ibm-grafana-operator
      containers:
        - name: ibm-grafana-operator
          # Replace this with the built image name
          image: quay.io/dongwangdw/grafana-operator:v0.1
          command:
          - ibm-grafana-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-grafana-operator"
