apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
  name: ibm-monitoring-grafana-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-grafana-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/managed-by: ibm-monitoring-grafana-operator
        name: ibm-monitoring-grafana-operator
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-grafana-operator
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: grafana
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-monitoring-grafana-operator
          command:
          - ibm-monitoring-grafana-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-grafana-operator"
            - name: GRAFANA_IMAGE
              value: quay.io/opencloudio/grafana@sha256:f394f73be7a7134eafed417260cceb361b67a72394e165b50fc254f6cdc70829
            - name: ROUTER_IMAGE
              value: quay.io/opencloudio/icp-management-ingress@sha256:c49e551f9f68f2e024a8a50e35f2ce4a6ec86f169d9bfb489b47fa6e8e216571
            - name: DASHBOARD_CTL_IMAGE
              value: quay.io/opencloudio/dashboard-controller@sha256:6bd67ebe4487eb98a8bfeab451fa9f0344b5e7806b27eb1d00009d1897f95c27
            - name: INIT_IMAGE
              value: quay.io/opencloudio/icp-initcontainer@sha256:9aad9fd724ec9308bec711d7738b5f0ae0c37a72ffb19a26dbcf622f1a603e89
