apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "Grafana",
          "metadata": {
            "name": "ibm-monitoring"
          },
          "spec": {
            "baseImage": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/grafana",
            "baseImageTag": "v6.5.2-build.1",
            "routerImage": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-management-ingress",
            "routerImageTag": "2.5.1",
            "dashboardCtlImage": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/dashboard-controller",
            "dashboardCtlImageTag": "v1.2.0-build.2",
            "initImage": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-initcontainer",
            "initImageTag": "1.0.0-build.2",
            "imagePullSecrets": [
              "infra-registry-key"
            ],
            "ipVersion": "4",
            "isHub": false,
            "resources": {
              "dashboard": 1,
              "grafana": 2,
              "router": 1
            },
            "service": {
              "ports": [
                {
                  "name": "ibm-monitoring-grafana",
                  "port": 3000,
                  "protocol": "TCP"
                }
              ]
            },
            "tlsClientSecretName": "ibm-monitoring-client-certs",
            "tlsSecretName": "ibm-monitoring-certs",
            "prometheusServiceName": "ibm-monitoring-prometheus",
            "prometheusServicePort": 9090
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-grafana-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Grafana is the Schema for the grafanas API
      kind: Grafana
      name: grafanas.operator.ibm.com
      version: v1alpha1
      displayName: IBM Monitoring Grafana
    - description: MonitoringDashboard is the Schema for Grafana Dashboard
      kind: MonitoringDashboard
      name: monitoringdashboards.monitoringcontroller.cloud.ibm.com
      version: v1
      displayName: IBM Grafana Dashboard
  description: Grafana Operator for IBM common service monitoring stack
  displayName: Ibm Grafana Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - services
          - nodes
          - nodes/proxy
          - endpoints
          - pods
          - configmaps
          - namespaces
          verbs:
          - get
          - list
          - watch
        - nonResourceURLs:
          - /metrics
          verbs:
          - get
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - monitoringcontroller.cloud.ibm.com
          resources:
          - monitoringdashboards
          verbs:
          - '*'
        serviceAccountName: ibm-monitoring-grafana
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - statefulsets
          - replicasets
          verbs:
          - '*'
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - certificates
          verbs:
          - '*'
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - clusterissuers
          verbs:
          - use
        - apiGroups:
          - operator.ibm.com
          resources:
          - grafanas
          - grafanas/finalizers
          - grafanas/status
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - monitoringcontroller.cloud.ibm.com
          resources:
          - monitoringdashboards
          verbs:
          - '*'
        serviceAccountName: ibm-monitoring-grafana-operator
      deployments:
      - name: ibm-monitoring-grafana-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-monitoring-grafana-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-monitoring-grafana-operator
              annotations:
                productName: IBM Cloud Platform Common Services
                productID: "068a62892a1e4db39641342e592daa25"
                productVersion: "3.3.0"
                productMetric: FREE
            spec:
              containers:
              - command:
                - ibm-grafana-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-monitoring-grafana-operator
                image: quay.io/opencloudio/ibm-monitoring-grafana-operator
                imagePullPolicy: Always
                name: grafana
                resources: {}
              serviceAccountName: ibm-monitoring-grafana-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: IBM
  replaces: ibm-grafana-operator.v0.0.0
  version: 0.0.1
